### PR TITLE
Clean code and creating minified

### PR DESCRIPTION
**Pull request by jesusvilla**

### CODE REVIEW

**Comment by Shemesh** [comment]
hi @jesusvilla 
correct me if i'm wrong - the only real difference i see in your code is not using the callback in scrollTo() function, and instead calling directly reCalcSides() from inside it.

all the other diffs i see are spacing and tabing.

am i right?

**Comment by jesusvilla** [comment]
hi @Shemesh
Yes, that's right, the rest (spacing and tabing) is generated by the ide (netbeans).

**Comment by Shemesh** [comment]
why do you think using direct call is better than a callback?
using callback gives more freedom and control.

**Comment by jesusvilla** [comment]
because that callback is only used to make the reCalcSides(), at least so far.

**Comment by Shemesh** [comment]
for better modularity of the code i think it is better to use a **callback**, it also gives a better separation of responsibility (of functions) and as said - more freedom and control.
i will revert your changes, OK?

**Pull request merged**
