### PR TITLE
Merge remote-tracking branch 'refs/remotes/VersifitTechnologies/master'

### PR DESCRIPTION
**Pull request by jesusvilla**

### CODE REVIEW

**Comment by Shemesh** [comment]
hi @jesusvilla,
i need some clarification... your branch was already merged in merge #34.
what is this current merge for? what are the changes comparing to the latest master v2.2.3?

**Comment by jesusvilla** [comment]
Hi @Shemesh,
No, no changes, that was a mistake on my part, wanting to pull from this project. The second commit I did: 'Clear code', that does have small changes in $scope.scrollTo, there is no callback.

**Comment by Shemesh** [comment]
hi, @jesusvilla 
so what do you suggest? can you delete the redundant commits?

**Comment by jesusvilla** [comment]
hi @Shemesh
Sorry, I do not know how to do it, you could only reverse this commit for me? Leaving the commit: 'Clean code'.

**Comment by jesusvilla** [comment]
Best eliminates those two commits, then climb another commit, excuse me.

**Pull request merged**
